### ISSUE TITLE
Request to update solutions of gfsm, ccvt and cexp

### ISSUE THREAD

**Issue by dopederre** [24thsaint/ProxorSolutions-C-Exam-V1.1#2]
Hey! Rave Arevalo. Loved your work. I too am an aspiring programmer.
I will be having my Proxor C exam in few weeks. I am stuck with some tasks. It would be a greattt!! help if you would put up your solutions of "gfsm", "ccvt" and "cexp". i am having partially correct solution of gfsm, but some test cases are failing. Please please put up your solutions.
Thanking you.

![Capture1](https://user-images.githubusercontent.com/66127607/83275648-0b78ab00-a1ed-11ea-998f-8f4c062ac3eb.PNG)

**Comment by 24thsaint** [comment]
Hello,

I am sorry but this project has been put on hold indefinitely in favor of the Java version: https://github.com/24thsaint/Proxor-Solutions-ExamStudyV6

I sincerely apologize.
